name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Heroku Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HEROKU_USERNAME }}
          password: ${{ secrets.HEROKU_API_KEY }}
      
      - name: Build and push Docker image
        uses: heroku/actions/build@v4
        with:
          app-name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile: Dockerfile
          context: ./
      
      - name: Release to Heroku
        uses: heroku/actions/deploy@v4
        with:
          app-name: ${{ secrets.HEROKU_APP_NAME }}
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}
